version: '3.8'
services:
  db:
    image: postgres
    container_name: pg_container
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
